name: deploy server

on:
  push:
    branches:
      - main
    paths:
      - "apps/dramacom-server"

jobs:
  deploy:
    name: deploy server
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: "apps/dramacom-server"
    steps:
      - uses: actions/checkout@v4

      - name: server deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}